Added ed25519 to x25519 conversion methods
sodiumoxide/sodiumoxide pull request #362
Opened 2019-08-18 05:11 UTC by ryankurte

Allowing use of signing keys for encryption/decryption if required, as in the [docs](https://download.libsodium.org/doc/advanced/ed25519-curve25519). This is implemented as `TryInto` on `&T` so keys are not consumed in the conversion.

I'm struggling to see if/where there are test vectors in the underlying [library](https://github.com/jedisct1/libsodium/blob/927dfe8e2eaa86160d3ba12a7e3258fbc322909c/test/default/ed25519_convert.c), so the tests are p primitive.

2019-11-11 00:39 UTC, ryankurte commented
hey hey, anything else i need to do here?

2019-11-11 11:25 UTC, kpp commented
https://github.com/sodiumoxide/sodiumoxide/pull/361#issuecomment-519459157

2020-10-03 11:22 UTC, sekhat commented
Hey guys, is there anything holding this pull request up?

2020-10-08 04:41 UTC, dnaq commented
Hi,

Sorry for the extremely long delay.

I think I might prefer the approach of exposing conversion functions instead of TryInto, even though TryInto is more idiomatic rust we don't really want people to use this functionality unless they really need it. I think TryInto might lead to people using it without considering alternative solutions.

However I'm not the maintainer anymore, so I'll do a code review as well if @kpp differs in his opinion.

2020-10-08 04:45 UTC, dnaq requested changes

2020-10-08 04:45 UTC, dnaq commented on src/crypto/sign/ed25519.rs
> +use crate::crypto::box_::{
Maybe do`use crate::crypto::box` instead of renaming the constants.

2020-10-08 04:45 UTC, dnaq commented on src/crypto/sign/ed25519.rs
> +                (&mut x25519_pk.0).as_mut_ptr(),
This feels like double conversions. Shouldn't `pk.0.as_mut_ptr()` be enough?

2020-10-08 04:45 UTC, dnaq commented on src/crypto/sign/ed25519.rs
> +                (&ed25519_pk.0).as_ptr(),
Same as above

2020-10-08 04:45 UTC, dnaq commented on src/crypto/sign/ed25519.rs
> +                (&mut x25519_sk.0).as_mut_ptr(),
Same

2020-10-08 04:45 UTC, dnaq commented on src/crypto/sign/ed25519.rs
> +                (&ed25519_sk.0).as_ptr(),
Same

2021-01-22 11:46 UTC, sekhat commented
I've gone ahead and implemented the changes requested here as PR #456.

2021-01-24 21:53 UTC, closed without merging