feat: sodium_pad/unpad
sodiumoxide/sodiumoxide pull request #432
Opened 2020-07-29 22:24 UTC by klittlepage

Exposes the sodium_pad and sodium_unpad functions.
Closes https://github.com/sodiumoxide/sodiumoxide/issues/426

2020-10-14 08:01 UTC, tasn commented
Any updates on getting this merged? Would love to be able to use it... Thanks!

2020-10-14 09:02 UTC, kpp requested changes

2020-10-14 09:02 UTC, kpp commented on src/padding.rs
> +pub fn pad(buf: &mut [u8], unpadded_buflen: usize, blocksize: usize) -> Result<usize, ()> {
`unpadded_buflen` can be extracted from buf.len()

2020-10-14 13:19 UTC, jedisct1 commented on src/padding.rs
> +pub fn pad(buf: &mut [u8], unpadded_buflen: usize, blocksize: usize) -> Result<usize, ()> {
Since the same buffer is used for input and output, this is not going to work without explicitly providing the original length.

That being said, that interface is a bit awkward to use. I'd just return a `Vec` instead.

2020-10-14 14:20 UTC, klittlepage commented on src/padding.rs
> +pub fn pad(buf: &mut [u8], unpadded_buflen: usize, blocksize: usize) -> Result<usize, ()> {
Happy to change the code to copy and return a `Vec`, or leave it; @jedisct1 nailed the reason as to why I took `unpadded_buflen` explicitly.

2020-10-14 15:02 UTC, kpp commented on src/padding.rs
> +pub fn pad(buf: &mut [u8], unpadded_buflen: usize, blocksize: usize) -> Result<usize, ()> {
What if the padding data overflow the provided buf? Shouldn't we check unpadded_buflen + block_size <= buf?

2020-10-14 15:07 UTC, klittlepage commented on src/padding.rs
> +pub fn pad(buf: &mut [u8], unpadded_buflen: usize, blocksize: usize) -> Result<usize, ()> {
That invariant is already covered on the linsodium side; if there’s not enough tail room in the buffer, a non zero exit code is returned, and we’d error on the rust side.

2020-10-14 16:28 UTC, kpp submitted a review, later dismissed

2020-10-14 16:30 UTC, kpp commented
bors: r+

2020-10-14 17:58 UTC, kpp commented
bors: retry

2020-10-14 19:48 UTC, kpp commented
omg?

2020-10-14 19:54 UTC, klittlepage commented
Bad bors!

Want me to push with master merged in and see if triggering a build off of a new commit hash works?

2020-10-14 20:32 UTC, jedisct1 commented on src/padding.rs
> +pub fn pad(buf: &mut [u8], unpadded_buflen: usize, blocksize: usize) -> Result<usize, ()> {
Seriously, just return a `Vec`. Applications shouldn't have to do math and deal with errors.

2020-10-14 21:12 UTC, kpp commented
Yes please

2020-10-15 05:37 UTC, tasn commented on src/padding.rs
> +pub fn pad(buf: &mut [u8], unpadded_buflen: usize, blocksize: usize) -> Result<usize, ()> {
In addition, the rest of the sodiumoxide code returns `Vec`s, so it'd also be more consistent. Maybe something like:
```rust
pub fn pad(buf: &[u8], blocksize: usize) -> Result<Vec<u8>, ()> {
    let len = buf.len();
    let missing = blocksize - (len % blocksize);
    let padding = len + missing;
    let mut ret = vec![0; padding];
    ret[..len].copy_from_slice(buf);

    sodium_padding::pad(&mut ret[..], len, blocksize).map_err(|_| Error::Padding("Failed padding"))?;

    Ok(ret)
}

pub fn unpad(buf: &[u8], blocksize: usize) -> Result<Vec<u8>, ()> {
    let len = buf.len();
    if len == 0 {
        return Ok(vec![0; 0]);
    }

    let mut buf = buf.to_vec();

    let new_len = sodium_padding::unpad(&mut buf[..], len, blocksize)?;
    buf.truncate(new_len);
    Ok(buf)
}
```
Or heck, may pass the ownership of the buffer to the function and then let it resize it so that the padding/unpadding can potentially be done in place?

2020-10-15 09:11 UTC, kpp commented
bors: r+

2020-10-15 15:09 UTC, klittlepage commented
@kpp it appears that Travis is borked, which would explain why Bors is timing out. I forced a new build; appveyor built fine but Travis has been hung on `Expected — Waiting for status to be reported` for an hour.

2020-10-15 15:36 UTC, kpp commented
How about switching to Github Actions?

2020-10-15 21:31 UTC, klittlepage commented
So here's a fun one @kpp. The CI pipeline is breaking because of an issue with compiling `cargo-travis` on the [coverage build](https://travis-ci.org/github/sodiumoxide/sodiumoxide/jobs/736056548). Everything else builds fine.

[This](https://travis-ci.org/github/sodiumoxide/sodiumoxide/jobs/713798107) was the last passing build, so I tried using `1.45.1` in the build pipeline. And...it fails with [the same error](https://travis-ci.org/github/sodiumoxide/sodiumoxide/jobs/736179577). Same rust toolchain. Same cargo lock files. Same everything. As a sanity check, I did the same test on my local machine. Same issue there. I have no idea how this is possible.

2020-10-28 09:52 UTC, kpp commented
bors: r+

2020-11-24 11:06 UTC, kpcyrd commented
@klittlepage we've fixed the ci, could you rebase your branch? :)

2020-11-24 16:03 UTC, klittlepage commented
@kpcyrd  👍 on the new build pipeline. Rebased and good to go.

2020-11-24 20:06 UTC, kpp requested changes

2020-11-24 20:06 UTC, kpp commented on src/padding.rs
> +use prelude::*;
Seems like we don't need this import at all

2020-11-24 21:20 UTC, kpcyrd commented
I think something went wrong during rebase, try to only pick the latest commit :)

2020-11-24 21:26 UTC, klittlepage commented
I'm trying (unsuccessfully) to rebase and linearize the history. When I reorder the commit history, Github tries to include too much history in the PR. When I rebase in a way that Github likes, I end up with two `feat: sodium_pad/unpad` commits (one for today, and the original one on July 29th.

Any ideas?

2020-11-24 22:20 UTC, kpcyrd commented
@klittlepage I rebased your branch, I'm not sure what the quickfix commit is for though :)

2020-11-24 22:29 UTC, klittlepage commented
@kpcyrd thanks! Would you mind letting me know what the magic `git` incantations were for future edification?

Quickfix was in reference to @kpp 's observation that the `prelude` wasn't necessary; I planned on doing a fixup onto 98f4675 before things went off the rails.

2020-11-24 22:30 UTC, kpp commented
@klittlepage try to `git rebase -i ... ` and only reorder commits, only then `git rebase -i` + fixup. Also `git rebase -imp` helps to remove merge commits.

2020-11-24 22:31 UTC, kpp approved these changes

2020-11-24 22:45 UTC, kpcyrd commented
This is how I rebased, note that it refused to create empty commits because the changes are already in master:
<details>
% git co -b feat-padding
Switched to a new branch 'feat-padding'
% git rebase -i origin/master  
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git rebase --skip'
interactive rebase in progress; onto e1051c87
Last commands done (2 commands done):
   pick d76263c0 feat: sodium_pad/unpad
   pick 3c58c224 feat: expose randombytes_buf_deterministic
Next commands to do (2 remaining commands):
   pick eae988e5 Add support for the AES256-GCM AEAD construction
   pick f340d042 quickfix
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'feat-padding' on 'e1051c87'.
  (all conflicts fixed: run "git rebase --continue")

Untracked files:
  (use "git add <file>..." to include in what will be committed)
    libsodium-sys/patch
    libsodium-sys/patch2

nothing added to commit but untracked files present (use "git add" to track)
Could not apply 3c58c224... feat: expose randombytes_buf_deterministic
% git st
interactive rebase in progress; onto e1051c87
Last commands done (2 commands done):
   pick d76263c0 feat: sodium_pad/unpad
   pick 3c58c224 feat: expose randombytes_buf_deterministic
Next commands to do (2 remaining commands):
   pick eae988e5 Add support for the AES256-GCM AEAD construction
   pick f340d042 quickfix
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'feat-padding' on 'e1051c87'.
  (all conflicts fixed: run "git rebase --continue")

Untracked files:
  (use "git add <file>..." to include in what will be committed)
    libsodium-sys/patch
    libsodium-sys/patch2

nothing added to commit but untracked files present (use "git add" to track)
% git rebase --continue 
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git rebase --skip'
interactive rebase in progress; onto e1051c87
Last commands done (3 commands done):
   pick 3c58c224 feat: expose randombytes_buf_deterministic
   pick eae988e5 Add support for the AES256-GCM AEAD construction
  (see more in file .git/rebase-merge/done)
Next command to do (1 remaining command):
   pick f340d042 quickfix
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'feat-padding' on 'e1051c87'.
  (all conflicts fixed: run "git rebase --continue")

Untracked files:
  (use "git add <file>..." to include in what will be committed)
    libsodium-sys/patch
    libsodium-sys/patch2

nothing added to commit but untracked files present (use "git add" to track)
Could not apply eae988e5... Add support for the AES256-GCM AEAD construction
% git st
interactive rebase in progress; onto e1051c87
Last commands done (3 commands done):
   pick 3c58c224 feat: expose randombytes_buf_deterministic
   pick eae988e5 Add support for the AES256-GCM AEAD construction
  (see more in file .git/rebase-merge/done)
Next command to do (1 remaining command):
   pick f340d042 quickfix
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'feat-padding' on 'e1051c87'.
  (all conflicts fixed: run "git rebase --continue")

Untracked files:
  (use "git add <file>..." to include in what will be committed)
    libsodium-sys/patch
    libsodium-sys/patch2

nothing added to commit but untracked files present (use "git add" to track)
% git rebase --continue 
Successfully rebased and updated refs/heads/feat-padding.
% git show
commit 93cee30d1cc75a79cfeb48f343af1aacc02d167c (HEAD -> feat-padding)
Author: Kelly Littlepage <kelly@onechronos.com>
Date:   Tue Nov 24 13:30:02 2020 -0700

    quickfix

diff --git a/src/padding.rs b/src/padding.rs
index 34bd4630..828c6ca6 100644
--- a/src/padding.rs
+++ b/src/padding.rs
@@ -18,8 +18,6 @@
 //! side channels for a given length & <block size mask> value.
 
 use ffi;
-#[cfg(not(feature = "std"))]
-use prelude::*;
 
 /// The `pad()` function adds padding data to a buffer buf whose original size is `unpadded_buflen`
 /// in order to extend its total length to a multiple of blocksize.
% 
% git push -fu klittlepage feat-padding 
Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 4 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 2.18 KiB | 2.18 MiB/s, done.
Total 9 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
git gTo github.com:klittlepage/sodiumoxide.git
 + f340d042...93cee30d feat-padding -> feat-padding (forced update)
Branch 'feat-padding' set up to track remote branch 'feat-padding' from 'klittlepage'.
% 
</details>

2020-11-24 22:46 UTC, kpcyrd commented
bors r+

2020-11-24 22:48 UTC, klittlepage commented
@kpp @kpcyrd thank you! I did the reordering and the fixup in one rebase, which caused problems.

2020-11-24 22:55 UTC, merged