Maintenance fixes for dependency updates
sodiumoxide/sodiumoxide pull request #478
Opened 2022-06-13 10:34 UTC by Xiretza

Hi! I know the README says you'll only accept security fixes, but I'm trying my luck with sneaking these maintenance fixes in anyway.

`ed25519` version 1.3.0 changed `Signature::new()` to panic on invalid data, which broke tests and caused deprecation warnings; I fixed that and bumped the dep version.

`build.rs` uses `cc::Tool::cflags_env()`, which was introduced in cc 1.0.3. Specifying a too-low dependency breaks any `-Z minimum-versions` builds downstream, I bumped the dep version there as well.

I also prepared a release commit that bumps the version numbers and updates the changelog, I can of course remove that though if you want to do it yourself.

2022-06-13 15:40 UTC, kpcyrd commented on src/crypto/sign/ed25519.rs
> +                if let Ok(sig) = Signature::from_bytes(&sig) {
I think the test should fail if `Signature::from_bytes` returns `Err(_)` :)

2022-06-14 15:07 UTC, kpcyrd commented on src/crypto/sign/ed25519.rs
> +                if let Ok(sig) = Signature::from_bytes(&sig) {
Ah I see, this is fine then :)

2022-06-14 19:56 UTC, kpp approved these changes, later dismissed

2022-07-23 08:19 UTC, kpp requested changes
You can call `set_len` after calling `crypto_box_easy`. It will fix the issue.

2022-07-23 09:20 UTC, kpp submitted a review, later dismissed

2022-07-23 18:29 UTC, kpp commented
@Xiretza can you fix CI?

2022-07-24 06:29 UTC, Xiretza commented
Not easily, no. The latest versions of our dependencies simply don't build with rustc 1.36 anymore (because they use `edition="2021"`), in order to fix the build they'd either have to be manually pinned to an older version somehow (without affecting users of the library), or we'd have to mess around with the unstable [`-Z minimal-versions`](https://github.com/rust-lang/cargo/issues/5657). Not sure if either is worth it for a library that's unlikely to see many more contributions anyway.

2022-07-24 06:41 UTC, adamreichold commented
> Not easily, no. The latest versions of our dependencies simply don't build with rustc 1.36 anymore (because they use `edition="2021"`), in order to fix the build they'd either have to be manually pinned to an older version somehow (without affecting users of the library), or we'd have to mess around with the unstable [`-Z minimal-versions`](https://github.com/rust-lang/cargo/issues/5657). Not sure if either is worth it for a library that's unlikely to see many more contributions anyway.

A possibly simpler alternative would be to create an alternative `Cargo.lock` once by locally using `-Z minimal-versions` or `cargo update --precise` and check that into the repository. It could then be used for the MSRV build job without adding a lot of automation besides moving the file into place.

Of course, this could still be considered unreasonable effort consider the status of the crate.

2022-07-24 12:15 UTC, kpp commented
Or you can bump msrv to satisfy CI. Don’t forget to update the docs in Readme.

2022-07-24 15:13 UTC, Xiretza commented
Sure, if that's what you want to do - I tried to keep the changes as minimal as possible (only requiring minor version bumps of transitive dependencies), but simply increasing the MSRV from 1.36 to 1.56 would of course also fix this.

2022-07-24 16:37 UTC, kpp commented
Well, yes. Would you please do it?

2022-07-25 09:18 UTC, Xiretza commented
Of course, done! I also fixed the clippy warnings in `build.rs`.

2022-07-25 11:00 UTC, kpp approved these changes

2022-07-31 05:33 UTC, pinkforest commented
Thanks all for keeping the last light on this crate - it's still used by a lot :purple_heart:

2022-08-01 09:31 UTC, kpp commented
bors r+

2022-08-01 09:41 UTC, merged

2022-08-01 14:32 UTC, kpp commented
@dnaq can you publish a new release or give someone else rights to do that?

2022-08-01 14:51 UTC, pinkforest commented
You could add crate ownership to the team organisation for sodiumoxide - I think @Dylan-DPC-zz has the admin ?
Like f.ex. see cargo-geiger is owned by `github:rust-secure-code:cargo-geiger-admins` which is a distinct team in our WG
That would make anyone belonging into a certain team able to publish and the maintainer bus can move in the github org team
https://crates.io/teams/github:rust-secure-code:cargo-geiger-admins
https://crates.io/crates/cargo-geiger

2022-08-01 14:58 UTC, Dylan-DPC commented
I dont have permissions on crates.io for it. I am ready if they want to pass it to me

2022-09-03 20:10 UTC, dnaq commented
I'm looking at doing a release with the changes from this pull request, but there are a lot of unrelated changes as well, mostly related to the order of set_length() calls and so on. Due to me not having the time to do any code review of those changes (even though they look correct with a cursory glance) I'm going to have to back out the changes from this pull request and reopen it.

2022-09-03 20:23 UTC, dnaq commented
Sorry, decided to archive the project completely. Feel free to fork.